project:
  type: website
  output-dir: docs

website:
  title: "Bayesian Business by Brandon"
  navbar:
    right:
      - href: about.qmd
        text: About 
      - icon: github
        href: https://github.com/devscotte
      - icon: linkedin
        href: https://www.linkedin.com/in/brandon-scott-5a7139211/
format:
  html:
    theme: lux
    css: styles.css



